// <auto-generated />
namespace Fastigheter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class KodförfälthanteringavenkoppladtabelliCRUDhantering : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KodförfälthanteringavenkoppladtabelliCRUDhantering));
        
        string IMigrationMetadata.Id
        {
            get { return "201802201223080_Kod för fälthantering av en kopplad tabell i CRUD-hantering"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
