// <auto-generated />
namespace Fastigheter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _4bostäderi2fastighetermednr14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4bostäderi2fastighetermednr14));
        
        string IMigrationMetadata.Id
        {
            get { return "201802201357409_4 bostäder i 2 fastigheter med nr. 1-4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
